// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sdaemonset"
)

// K8sDaemonSet is the model entity for the K8sDaemonSet schema.
type K8sDaemonSet struct {
	config `json:"-"`
	// ID of the ent.
	ID uint `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// K8sClusterId holds the value of the "k8sClusterId" field.
	K8sClusterId uint `json:"k8sClusterId,omitempty"`
	// K8sNamespaceId holds the value of the "k8sNamespaceId" field.
	K8sNamespaceId uint `json:"k8sNamespaceId,omitempty"`
	// K8sObjectId holds the value of the "k8sObjectId" field.
	K8sObjectId uint `json:"k8sObjectId,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*K8sDaemonSet) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case k8sdaemonset.FieldID, k8sdaemonset.FieldK8sClusterId, k8sdaemonset.FieldK8sNamespaceId, k8sdaemonset.FieldK8sObjectId:
			values[i] = new(sql.NullInt64)
		case k8sdaemonset.FieldName:
			values[i] = new(sql.NullString)
		case k8sdaemonset.FieldCreatedAt, k8sdaemonset.FieldUpdatedAt, k8sdaemonset.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type K8sDaemonSet", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the K8sDaemonSet fields.
func (kds *K8sDaemonSet) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case k8sdaemonset.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			kds.ID = uint(value.Int64)
		case k8sdaemonset.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				kds.CreatedAt = value.Time
			}
		case k8sdaemonset.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				kds.UpdatedAt = value.Time
			}
		case k8sdaemonset.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				kds.DeletedAt = value.Time
			}
		case k8sdaemonset.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				kds.Name = value.String
			}
		case k8sdaemonset.FieldK8sClusterId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field k8sClusterId", values[i])
			} else if value.Valid {
				kds.K8sClusterId = uint(value.Int64)
			}
		case k8sdaemonset.FieldK8sNamespaceId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field k8sNamespaceId", values[i])
			} else if value.Valid {
				kds.K8sNamespaceId = uint(value.Int64)
			}
		case k8sdaemonset.FieldK8sObjectId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field k8sObjectId", values[i])
			} else if value.Valid {
				kds.K8sObjectId = uint(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this K8sDaemonSet.
// Note that you need to call K8sDaemonSet.Unwrap() before calling this method if this K8sDaemonSet
// was returned from a transaction, and the transaction was committed or rolled back.
func (kds *K8sDaemonSet) Update() *K8sDaemonSetUpdateOne {
	return (&K8sDaemonSetClient{config: kds.config}).UpdateOne(kds)
}

// Unwrap unwraps the K8sDaemonSet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (kds *K8sDaemonSet) Unwrap() *K8sDaemonSet {
	tx, ok := kds.config.driver.(*txDriver)
	if !ok {
		panic("ent: K8sDaemonSet is not a transactional entity")
	}
	kds.config.driver = tx.drv
	return kds
}

// String implements the fmt.Stringer.
func (kds *K8sDaemonSet) String() string {
	var builder strings.Builder
	builder.WriteString("K8sDaemonSet(")
	builder.WriteString(fmt.Sprintf("id=%v", kds.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(kds.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(kds.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", deleted_at=")
	builder.WriteString(kds.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(kds.Name)
	builder.WriteString(", k8sClusterId=")
	builder.WriteString(fmt.Sprintf("%v", kds.K8sClusterId))
	builder.WriteString(", k8sNamespaceId=")
	builder.WriteString(fmt.Sprintf("%v", kds.K8sNamespaceId))
	builder.WriteString(", k8sObjectId=")
	builder.WriteString(fmt.Sprintf("%v", kds.K8sObjectId))
	builder.WriteByte(')')
	return builder.String()
}

// K8sDaemonSets is a parsable slice of K8sDaemonSet.
type K8sDaemonSets []*K8sDaemonSet

func (kds K8sDaemonSets) config(cfg config) {
	for _i := range kds {
		kds[_i].config = cfg
	}
}
