// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8snamespace"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/predicate"
)

// K8sNamespaceQuery is the builder for querying K8sNamespace entities.
type K8sNamespaceQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.K8sNamespace
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the K8sNamespaceQuery builder.
func (knq *K8sNamespaceQuery) Where(ps ...predicate.K8sNamespace) *K8sNamespaceQuery {
	knq.predicates = append(knq.predicates, ps...)
	return knq
}

// Limit adds a limit step to the query.
func (knq *K8sNamespaceQuery) Limit(limit int) *K8sNamespaceQuery {
	knq.limit = &limit
	return knq
}

// Offset adds an offset step to the query.
func (knq *K8sNamespaceQuery) Offset(offset int) *K8sNamespaceQuery {
	knq.offset = &offset
	return knq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (knq *K8sNamespaceQuery) Unique(unique bool) *K8sNamespaceQuery {
	knq.unique = &unique
	return knq
}

// Order adds an order step to the query.
func (knq *K8sNamespaceQuery) Order(o ...OrderFunc) *K8sNamespaceQuery {
	knq.order = append(knq.order, o...)
	return knq
}

// First returns the first K8sNamespace entity from the query.
// Returns a *NotFoundError when no K8sNamespace was found.
func (knq *K8sNamespaceQuery) First(ctx context.Context) (*K8sNamespace, error) {
	nodes, err := knq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{k8snamespace.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (knq *K8sNamespaceQuery) FirstX(ctx context.Context) *K8sNamespace {
	node, err := knq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first K8sNamespace ID from the query.
// Returns a *NotFoundError when no K8sNamespace ID was found.
func (knq *K8sNamespaceQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = knq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{k8snamespace.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (knq *K8sNamespaceQuery) FirstIDX(ctx context.Context) uint {
	id, err := knq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single K8sNamespace entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one K8sNamespace entity is not found.
// Returns a *NotFoundError when no K8sNamespace entities are found.
func (knq *K8sNamespaceQuery) Only(ctx context.Context) (*K8sNamespace, error) {
	nodes, err := knq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{k8snamespace.Label}
	default:
		return nil, &NotSingularError{k8snamespace.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (knq *K8sNamespaceQuery) OnlyX(ctx context.Context) *K8sNamespace {
	node, err := knq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only K8sNamespace ID in the query.
// Returns a *NotSingularError when exactly one K8sNamespace ID is not found.
// Returns a *NotFoundError when no entities are found.
func (knq *K8sNamespaceQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = knq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = &NotSingularError{k8snamespace.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (knq *K8sNamespaceQuery) OnlyIDX(ctx context.Context) uint {
	id, err := knq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of K8sNamespaces.
func (knq *K8sNamespaceQuery) All(ctx context.Context) ([]*K8sNamespace, error) {
	if err := knq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return knq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (knq *K8sNamespaceQuery) AllX(ctx context.Context) []*K8sNamespace {
	nodes, err := knq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of K8sNamespace IDs.
func (knq *K8sNamespaceQuery) IDs(ctx context.Context) ([]uint, error) {
	var ids []uint
	if err := knq.Select(k8snamespace.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (knq *K8sNamespaceQuery) IDsX(ctx context.Context) []uint {
	ids, err := knq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (knq *K8sNamespaceQuery) Count(ctx context.Context) (int, error) {
	if err := knq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return knq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (knq *K8sNamespaceQuery) CountX(ctx context.Context) int {
	count, err := knq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (knq *K8sNamespaceQuery) Exist(ctx context.Context) (bool, error) {
	if err := knq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return knq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (knq *K8sNamespaceQuery) ExistX(ctx context.Context) bool {
	exist, err := knq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the K8sNamespaceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (knq *K8sNamespaceQuery) Clone() *K8sNamespaceQuery {
	if knq == nil {
		return nil
	}
	return &K8sNamespaceQuery{
		config:     knq.config,
		limit:      knq.limit,
		offset:     knq.offset,
		order:      append([]OrderFunc{}, knq.order...),
		predicates: append([]predicate.K8sNamespace{}, knq.predicates...),
		// clone intermediate query.
		sql:  knq.sql.Clone(),
		path: knq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.K8sNamespace.Query().
//		GroupBy(k8snamespace.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (knq *K8sNamespaceQuery) GroupBy(field string, fields ...string) *K8sNamespaceGroupBy {
	group := &K8sNamespaceGroupBy{config: knq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := knq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return knq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.K8sNamespace.Query().
//		Select(k8snamespace.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (knq *K8sNamespaceQuery) Select(fields ...string) *K8sNamespaceSelect {
	knq.fields = append(knq.fields, fields...)
	return &K8sNamespaceSelect{K8sNamespaceQuery: knq}
}

func (knq *K8sNamespaceQuery) prepareQuery(ctx context.Context) error {
	for _, f := range knq.fields {
		if !k8snamespace.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if knq.path != nil {
		prev, err := knq.path(ctx)
		if err != nil {
			return err
		}
		knq.sql = prev
	}
	return nil
}

func (knq *K8sNamespaceQuery) sqlAll(ctx context.Context) ([]*K8sNamespace, error) {
	var (
		nodes = []*K8sNamespace{}
		_spec = knq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &K8sNamespace{config: knq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, knq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (knq *K8sNamespaceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := knq.querySpec()
	return sqlgraph.CountNodes(ctx, knq.driver, _spec)
}

func (knq *K8sNamespaceQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := knq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (knq *K8sNamespaceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   k8snamespace.Table,
			Columns: k8snamespace.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: k8snamespace.FieldID,
			},
		},
		From:   knq.sql,
		Unique: true,
	}
	if unique := knq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := knq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, k8snamespace.FieldID)
		for i := range fields {
			if fields[i] != k8snamespace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := knq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := knq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := knq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := knq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (knq *K8sNamespaceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(knq.driver.Dialect())
	t1 := builder.Table(k8snamespace.Table)
	columns := knq.fields
	if len(columns) == 0 {
		columns = k8snamespace.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if knq.sql != nil {
		selector = knq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range knq.predicates {
		p(selector)
	}
	for _, p := range knq.order {
		p(selector)
	}
	if offset := knq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := knq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// K8sNamespaceGroupBy is the group-by builder for K8sNamespace entities.
type K8sNamespaceGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (kngb *K8sNamespaceGroupBy) Aggregate(fns ...AggregateFunc) *K8sNamespaceGroupBy {
	kngb.fns = append(kngb.fns, fns...)
	return kngb
}

// Scan applies the group-by query and scans the result into the given value.
func (kngb *K8sNamespaceGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := kngb.path(ctx)
	if err != nil {
		return err
	}
	kngb.sql = query
	return kngb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := kngb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(kngb.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := kngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) StringsX(ctx context.Context) []string {
	v, err := kngb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = kngb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) StringX(ctx context.Context) string {
	v, err := kngb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(kngb.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := kngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) IntsX(ctx context.Context) []int {
	v, err := kngb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = kngb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) IntX(ctx context.Context) int {
	v, err := kngb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(kngb.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := kngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := kngb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = kngb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) Float64X(ctx context.Context) float64 {
	v, err := kngb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(kngb.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := kngb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := kngb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kngb *K8sNamespaceGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = kngb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (kngb *K8sNamespaceGroupBy) BoolX(ctx context.Context) bool {
	v, err := kngb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (kngb *K8sNamespaceGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range kngb.fields {
		if !k8snamespace.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := kngb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := kngb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (kngb *K8sNamespaceGroupBy) sqlQuery() *sql.Selector {
	selector := kngb.sql.Select()
	aggregation := make([]string, 0, len(kngb.fns))
	for _, fn := range kngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(kngb.fields)+len(kngb.fns))
		for _, f := range kngb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(kngb.fields...)...)
}

// K8sNamespaceSelect is the builder for selecting fields of K8sNamespace entities.
type K8sNamespaceSelect struct {
	*K8sNamespaceQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (kns *K8sNamespaceSelect) Scan(ctx context.Context, v interface{}) error {
	if err := kns.prepareQuery(ctx); err != nil {
		return err
	}
	kns.sql = kns.K8sNamespaceQuery.sqlQuery(ctx)
	return kns.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (kns *K8sNamespaceSelect) ScanX(ctx context.Context, v interface{}) {
	if err := kns.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Strings(ctx context.Context) ([]string, error) {
	if len(kns.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := kns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (kns *K8sNamespaceSelect) StringsX(ctx context.Context) []string {
	v, err := kns.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = kns.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (kns *K8sNamespaceSelect) StringX(ctx context.Context) string {
	v, err := kns.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Ints(ctx context.Context) ([]int, error) {
	if len(kns.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := kns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (kns *K8sNamespaceSelect) IntsX(ctx context.Context) []int {
	v, err := kns.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = kns.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (kns *K8sNamespaceSelect) IntX(ctx context.Context) int {
	v, err := kns.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(kns.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := kns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (kns *K8sNamespaceSelect) Float64sX(ctx context.Context) []float64 {
	v, err := kns.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = kns.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (kns *K8sNamespaceSelect) Float64X(ctx context.Context) float64 {
	v, err := kns.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(kns.fields) > 1 {
		return nil, errors.New("ent: K8sNamespaceSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := kns.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (kns *K8sNamespaceSelect) BoolsX(ctx context.Context) []bool {
	v, err := kns.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (kns *K8sNamespaceSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = kns.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8snamespace.Label}
	default:
		err = fmt.Errorf("ent: K8sNamespaceSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (kns *K8sNamespaceSelect) BoolX(ctx context.Context) bool {
	v, err := kns.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (kns *K8sNamespaceSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := kns.sql.Query()
	if err := kns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
