// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sobjecttag"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/predicate"
)

// K8sObjectTagQuery is the builder for querying K8sObjectTag entities.
type K8sObjectTagQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.K8sObjectTag
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the K8sObjectTagQuery builder.
func (kotq *K8sObjectTagQuery) Where(ps ...predicate.K8sObjectTag) *K8sObjectTagQuery {
	kotq.predicates = append(kotq.predicates, ps...)
	return kotq
}

// Limit adds a limit step to the query.
func (kotq *K8sObjectTagQuery) Limit(limit int) *K8sObjectTagQuery {
	kotq.limit = &limit
	return kotq
}

// Offset adds an offset step to the query.
func (kotq *K8sObjectTagQuery) Offset(offset int) *K8sObjectTagQuery {
	kotq.offset = &offset
	return kotq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (kotq *K8sObjectTagQuery) Unique(unique bool) *K8sObjectTagQuery {
	kotq.unique = &unique
	return kotq
}

// Order adds an order step to the query.
func (kotq *K8sObjectTagQuery) Order(o ...OrderFunc) *K8sObjectTagQuery {
	kotq.order = append(kotq.order, o...)
	return kotq
}

// First returns the first K8sObjectTag entity from the query.
// Returns a *NotFoundError when no K8sObjectTag was found.
func (kotq *K8sObjectTagQuery) First(ctx context.Context) (*K8sObjectTag, error) {
	nodes, err := kotq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{k8sobjecttag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) FirstX(ctx context.Context) *K8sObjectTag {
	node, err := kotq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first K8sObjectTag ID from the query.
// Returns a *NotFoundError when no K8sObjectTag ID was found.
func (kotq *K8sObjectTagQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = kotq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{k8sobjecttag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) FirstIDX(ctx context.Context) uint {
	id, err := kotq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single K8sObjectTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one K8sObjectTag entity is not found.
// Returns a *NotFoundError when no K8sObjectTag entities are found.
func (kotq *K8sObjectTagQuery) Only(ctx context.Context) (*K8sObjectTag, error) {
	nodes, err := kotq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{k8sobjecttag.Label}
	default:
		return nil, &NotSingularError{k8sobjecttag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) OnlyX(ctx context.Context) *K8sObjectTag {
	node, err := kotq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only K8sObjectTag ID in the query.
// Returns a *NotSingularError when exactly one K8sObjectTag ID is not found.
// Returns a *NotFoundError when no entities are found.
func (kotq *K8sObjectTagQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = kotq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = &NotSingularError{k8sobjecttag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) OnlyIDX(ctx context.Context) uint {
	id, err := kotq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of K8sObjectTags.
func (kotq *K8sObjectTagQuery) All(ctx context.Context) ([]*K8sObjectTag, error) {
	if err := kotq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return kotq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) AllX(ctx context.Context) []*K8sObjectTag {
	nodes, err := kotq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of K8sObjectTag IDs.
func (kotq *K8sObjectTagQuery) IDs(ctx context.Context) ([]uint, error) {
	var ids []uint
	if err := kotq.Select(k8sobjecttag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) IDsX(ctx context.Context) []uint {
	ids, err := kotq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (kotq *K8sObjectTagQuery) Count(ctx context.Context) (int, error) {
	if err := kotq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return kotq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) CountX(ctx context.Context) int {
	count, err := kotq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (kotq *K8sObjectTagQuery) Exist(ctx context.Context) (bool, error) {
	if err := kotq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return kotq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (kotq *K8sObjectTagQuery) ExistX(ctx context.Context) bool {
	exist, err := kotq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the K8sObjectTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (kotq *K8sObjectTagQuery) Clone() *K8sObjectTagQuery {
	if kotq == nil {
		return nil
	}
	return &K8sObjectTagQuery{
		config:     kotq.config,
		limit:      kotq.limit,
		offset:     kotq.offset,
		order:      append([]OrderFunc{}, kotq.order...),
		predicates: append([]predicate.K8sObjectTag{}, kotq.predicates...),
		// clone intermediate query.
		sql:  kotq.sql.Clone(),
		path: kotq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.K8sObjectTag.Query().
//		GroupBy(k8sobjecttag.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (kotq *K8sObjectTagQuery) GroupBy(field string, fields ...string) *K8sObjectTagGroupBy {
	group := &K8sObjectTagGroupBy{config: kotq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := kotq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return kotq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.K8sObjectTag.Query().
//		Select(k8sobjecttag.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (kotq *K8sObjectTagQuery) Select(fields ...string) *K8sObjectTagSelect {
	kotq.fields = append(kotq.fields, fields...)
	return &K8sObjectTagSelect{K8sObjectTagQuery: kotq}
}

func (kotq *K8sObjectTagQuery) prepareQuery(ctx context.Context) error {
	for _, f := range kotq.fields {
		if !k8sobjecttag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if kotq.path != nil {
		prev, err := kotq.path(ctx)
		if err != nil {
			return err
		}
		kotq.sql = prev
	}
	return nil
}

func (kotq *K8sObjectTagQuery) sqlAll(ctx context.Context) ([]*K8sObjectTag, error) {
	var (
		nodes = []*K8sObjectTag{}
		_spec = kotq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &K8sObjectTag{config: kotq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, kotq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (kotq *K8sObjectTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := kotq.querySpec()
	return sqlgraph.CountNodes(ctx, kotq.driver, _spec)
}

func (kotq *K8sObjectTagQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := kotq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (kotq *K8sObjectTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   k8sobjecttag.Table,
			Columns: k8sobjecttag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: k8sobjecttag.FieldID,
			},
		},
		From:   kotq.sql,
		Unique: true,
	}
	if unique := kotq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := kotq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, k8sobjecttag.FieldID)
		for i := range fields {
			if fields[i] != k8sobjecttag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := kotq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := kotq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := kotq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := kotq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (kotq *K8sObjectTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(kotq.driver.Dialect())
	t1 := builder.Table(k8sobjecttag.Table)
	columns := kotq.fields
	if len(columns) == 0 {
		columns = k8sobjecttag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if kotq.sql != nil {
		selector = kotq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range kotq.predicates {
		p(selector)
	}
	for _, p := range kotq.order {
		p(selector)
	}
	if offset := kotq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := kotq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// K8sObjectTagGroupBy is the group-by builder for K8sObjectTag entities.
type K8sObjectTagGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (kotgb *K8sObjectTagGroupBy) Aggregate(fns ...AggregateFunc) *K8sObjectTagGroupBy {
	kotgb.fns = append(kotgb.fns, fns...)
	return kotgb
}

// Scan applies the group-by query and scans the result into the given value.
func (kotgb *K8sObjectTagGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := kotgb.path(ctx)
	if err != nil {
		return err
	}
	kotgb.sql = query
	return kotgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := kotgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(kotgb.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := kotgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) StringsX(ctx context.Context) []string {
	v, err := kotgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = kotgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) StringX(ctx context.Context) string {
	v, err := kotgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(kotgb.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := kotgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) IntsX(ctx context.Context) []int {
	v, err := kotgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = kotgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) IntX(ctx context.Context) int {
	v, err := kotgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(kotgb.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := kotgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := kotgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = kotgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) Float64X(ctx context.Context) float64 {
	v, err := kotgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(kotgb.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := kotgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := kotgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (kotgb *K8sObjectTagGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = kotgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (kotgb *K8sObjectTagGroupBy) BoolX(ctx context.Context) bool {
	v, err := kotgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (kotgb *K8sObjectTagGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range kotgb.fields {
		if !k8sobjecttag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := kotgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := kotgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (kotgb *K8sObjectTagGroupBy) sqlQuery() *sql.Selector {
	selector := kotgb.sql.Select()
	aggregation := make([]string, 0, len(kotgb.fns))
	for _, fn := range kotgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(kotgb.fields)+len(kotgb.fns))
		for _, f := range kotgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(kotgb.fields...)...)
}

// K8sObjectTagSelect is the builder for selecting fields of K8sObjectTag entities.
type K8sObjectTagSelect struct {
	*K8sObjectTagQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (kots *K8sObjectTagSelect) Scan(ctx context.Context, v interface{}) error {
	if err := kots.prepareQuery(ctx); err != nil {
		return err
	}
	kots.sql = kots.K8sObjectTagQuery.sqlQuery(ctx)
	return kots.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (kots *K8sObjectTagSelect) ScanX(ctx context.Context, v interface{}) {
	if err := kots.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Strings(ctx context.Context) ([]string, error) {
	if len(kots.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := kots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (kots *K8sObjectTagSelect) StringsX(ctx context.Context) []string {
	v, err := kots.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = kots.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (kots *K8sObjectTagSelect) StringX(ctx context.Context) string {
	v, err := kots.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Ints(ctx context.Context) ([]int, error) {
	if len(kots.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := kots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (kots *K8sObjectTagSelect) IntsX(ctx context.Context) []int {
	v, err := kots.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = kots.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (kots *K8sObjectTagSelect) IntX(ctx context.Context) int {
	v, err := kots.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(kots.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := kots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (kots *K8sObjectTagSelect) Float64sX(ctx context.Context) []float64 {
	v, err := kots.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = kots.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (kots *K8sObjectTagSelect) Float64X(ctx context.Context) float64 {
	v, err := kots.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(kots.fields) > 1 {
		return nil, errors.New("ent: K8sObjectTagSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := kots.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (kots *K8sObjectTagSelect) BoolsX(ctx context.Context) []bool {
	v, err := kots.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (kots *K8sObjectTagSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = kots.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{k8sobjecttag.Label}
	default:
		err = fmt.Errorf("ent: K8sObjectTagSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (kots *K8sObjectTagSelect) BoolX(ctx context.Context) bool {
	v, err := kots.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (kots *K8sObjectTagSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := kots.sql.Query()
	if err := kots.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
