// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metricendpoint"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/predicate"
)

// MetricEndpointDelete is the builder for deleting a MetricEndpoint entity.
type MetricEndpointDelete struct {
	config
	hooks    []Hook
	mutation *MetricEndpointMutation
}

// Where appends a list predicates to the MetricEndpointDelete builder.
func (med *MetricEndpointDelete) Where(ps ...predicate.MetricEndpoint) *MetricEndpointDelete {
	med.mutation.Where(ps...)
	return med
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (med *MetricEndpointDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(med.hooks) == 0 {
		affected, err = med.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MetricEndpointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			med.mutation = mutation
			affected, err = med.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(med.hooks) - 1; i >= 0; i-- {
			if med.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = med.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, med.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (med *MetricEndpointDelete) ExecX(ctx context.Context) int {
	n, err := med.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (med *MetricEndpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: metricendpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: metricendpoint.FieldID,
			},
		},
	}
	if ps := med.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, med.driver, _spec)
}

// MetricEndpointDeleteOne is the builder for deleting a single MetricEndpoint entity.
type MetricEndpointDeleteOne struct {
	med *MetricEndpointDelete
}

// Exec executes the deletion query.
func (medo *MetricEndpointDeleteOne) Exec(ctx context.Context) error {
	n, err := medo.med.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{metricendpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (medo *MetricEndpointDeleteOne) ExecX(ctx context.Context) {
	medo.med.ExecX(ctx)
}
