// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/predicate"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/process"
)

// ProcessUpdate is the builder for updating Process entities.
type ProcessUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessMutation
}

// Where appends a list predicates to the ProcessUpdate builder.
func (pu *ProcessUpdate) Where(ps ...predicate.Process) *ProcessUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProcessUpdate) SetUpdatedAt(t time.Time) *ProcessUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *ProcessUpdate) SetDeletedAt(t time.Time) *ProcessUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetName sets the "name" field.
func (pu *ProcessUpdate) SetName(s string) *ProcessUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetPId sets the "pId" field.
func (pu *ProcessUpdate) SetPId(i int32) *ProcessUpdate {
	pu.mutation.ResetPId()
	pu.mutation.SetPId(i)
	return pu
}

// AddPId adds i to the "pId" field.
func (pu *ProcessUpdate) AddPId(i int32) *ProcessUpdate {
	pu.mutation.AddPId(i)
	return pu
}

// SetCmd sets the "cmd" field.
func (pu *ProcessUpdate) SetCmd(s string) *ProcessUpdate {
	pu.mutation.SetCmd(s)
	return pu
}

// SetInfo sets the "info" field.
func (pu *ProcessUpdate) SetInfo(s []string) *ProcessUpdate {
	pu.mutation.SetInfo(s)
	return pu
}

// SetClusterId sets the "clusterId" field.
func (pu *ProcessUpdate) SetClusterId(s string) *ProcessUpdate {
	pu.mutation.SetClusterId(s)
	return pu
}

// SetNodeId sets the "nodeId" field.
func (pu *ProcessUpdate) SetNodeId(s string) *ProcessUpdate {
	pu.mutation.SetNodeId(s)
	return pu
}

// SetContainerId sets the "containerId" field.
func (pu *ProcessUpdate) SetContainerId(s string) *ProcessUpdate {
	pu.mutation.SetContainerId(s)
	return pu
}

// Mutation returns the ProcessMutation object of the builder.
func (pu *ProcessUpdate) Mutation() *ProcessMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProcessUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	pu.defaults()
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProcessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProcessUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProcessUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProcessUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProcessUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := process.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
	if _, ok := pu.mutation.DeletedAt(); !ok {
		v := process.UpdateDefaultDeletedAt()
		pu.mutation.SetDeletedAt(v)
	}
}

func (pu *ProcessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   process.Table,
			Columns: process.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: process.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: process.FieldUpdatedAt,
		})
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: process.FieldDeletedAt,
		})
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldName,
		})
	}
	if value, ok := pu.mutation.PId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: process.FieldPId,
		})
	}
	if value, ok := pu.mutation.AddedPId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: process.FieldPId,
		})
	}
	if value, ok := pu.mutation.Cmd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldCmd,
		})
	}
	if value, ok := pu.mutation.Info(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: process.FieldInfo,
		})
	}
	if value, ok := pu.mutation.ClusterId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldClusterId,
		})
	}
	if value, ok := pu.mutation.NodeId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldNodeId,
		})
	}
	if value, ok := pu.mutation.ContainerId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldContainerId,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{process.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ProcessUpdateOne is the builder for updating a single Process entity.
type ProcessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProcessUpdateOne) SetUpdatedAt(t time.Time) *ProcessUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *ProcessUpdateOne) SetDeletedAt(t time.Time) *ProcessUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetName sets the "name" field.
func (puo *ProcessUpdateOne) SetName(s string) *ProcessUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetPId sets the "pId" field.
func (puo *ProcessUpdateOne) SetPId(i int32) *ProcessUpdateOne {
	puo.mutation.ResetPId()
	puo.mutation.SetPId(i)
	return puo
}

// AddPId adds i to the "pId" field.
func (puo *ProcessUpdateOne) AddPId(i int32) *ProcessUpdateOne {
	puo.mutation.AddPId(i)
	return puo
}

// SetCmd sets the "cmd" field.
func (puo *ProcessUpdateOne) SetCmd(s string) *ProcessUpdateOne {
	puo.mutation.SetCmd(s)
	return puo
}

// SetInfo sets the "info" field.
func (puo *ProcessUpdateOne) SetInfo(s []string) *ProcessUpdateOne {
	puo.mutation.SetInfo(s)
	return puo
}

// SetClusterId sets the "clusterId" field.
func (puo *ProcessUpdateOne) SetClusterId(s string) *ProcessUpdateOne {
	puo.mutation.SetClusterId(s)
	return puo
}

// SetNodeId sets the "nodeId" field.
func (puo *ProcessUpdateOne) SetNodeId(s string) *ProcessUpdateOne {
	puo.mutation.SetNodeId(s)
	return puo
}

// SetContainerId sets the "containerId" field.
func (puo *ProcessUpdateOne) SetContainerId(s string) *ProcessUpdateOne {
	puo.mutation.SetContainerId(s)
	return puo
}

// Mutation returns the ProcessMutation object of the builder.
func (puo *ProcessUpdateOne) Mutation() *ProcessMutation {
	return puo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProcessUpdateOne) Select(field string, fields ...string) *ProcessUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Process entity.
func (puo *ProcessUpdateOne) Save(ctx context.Context) (*Process, error) {
	var (
		err  error
		node *Process
	)
	puo.defaults()
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProcessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProcessUpdateOne) SaveX(ctx context.Context) *Process {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProcessUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProcessUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProcessUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := process.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
	if _, ok := puo.mutation.DeletedAt(); !ok {
		v := process.UpdateDefaultDeletedAt()
		puo.mutation.SetDeletedAt(v)
	}
}

func (puo *ProcessUpdateOne) sqlSave(ctx context.Context) (_node *Process, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   process.Table,
			Columns: process.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: process.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Process.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, process.FieldID)
		for _, f := range fields {
			if !process.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != process.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: process.FieldUpdatedAt,
		})
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: process.FieldDeletedAt,
		})
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldName,
		})
	}
	if value, ok := puo.mutation.PId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: process.FieldPId,
		})
	}
	if value, ok := puo.mutation.AddedPId(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: process.FieldPId,
		})
	}
	if value, ok := puo.mutation.Cmd(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldCmd,
		})
	}
	if value, ok := puo.mutation.Info(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: process.FieldInfo,
		})
	}
	if value, ok := puo.mutation.ClusterId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldClusterId,
		})
	}
	if value, ok := puo.mutation.NodeId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldNodeId,
		})
	}
	if value, ok := puo.mutation.ContainerId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: process.FieldContainerId,
		})
	}
	_node = &Process{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{process.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
