// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/container"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/node"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/proces"
)

// ProcesCreate is the builder for creating a Proces entity.
type ProcesCreate struct {
	config
	mutation *ProcesMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pc *ProcesCreate) SetCreatedAt(t time.Time) *ProcesCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *ProcesCreate) SetNillableCreatedAt(t *time.Time) *ProcesCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *ProcesCreate) SetUpdatedAt(t time.Time) *ProcesCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *ProcesCreate) SetNillableUpdatedAt(t *time.Time) *ProcesCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetDeletedAt sets the "deleted_at" field.
func (pc *ProcesCreate) SetDeletedAt(t time.Time) *ProcesCreate {
	pc.mutation.SetDeletedAt(t)
	return pc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pc *ProcesCreate) SetNillableDeletedAt(t *time.Time) *ProcesCreate {
	if t != nil {
		pc.SetDeletedAt(*t)
	}
	return pc
}

// SetName sets the "name" field.
func (pc *ProcesCreate) SetName(s string) *ProcesCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetPId sets the "pId" field.
func (pc *ProcesCreate) SetPId(i int32) *ProcesCreate {
	pc.mutation.SetPId(i)
	return pc
}

// SetCmd sets the "cmd" field.
func (pc *ProcesCreate) SetCmd(s string) *ProcesCreate {
	pc.mutation.SetCmd(s)
	return pc
}

// SetInfo sets the "info" field.
func (pc *ProcesCreate) SetInfo(s []string) *ProcesCreate {
	pc.mutation.SetInfo(s)
	return pc
}

// SetClusterId sets the "clusterId" field.
func (pc *ProcesCreate) SetClusterId(s string) *ProcesCreate {
	pc.mutation.SetClusterId(s)
	return pc
}

// SetNodeId sets the "nodeId" field.
func (pc *ProcesCreate) SetNodeId(s string) *ProcesCreate {
	pc.mutation.SetNodeId(s)
	return pc
}

// SetContainerId sets the "containerId" field.
func (pc *ProcesCreate) SetContainerId(s string) *ProcesCreate {
	pc.mutation.SetContainerId(s)
	return pc
}

// SetID sets the "id" field.
func (pc *ProcesCreate) SetID(u uint) *ProcesCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNodeProcessID sets the "node_process" edge to the Node entity by ID.
func (pc *ProcesCreate) SetNodeProcessID(id uint) *ProcesCreate {
	pc.mutation.SetNodeProcessID(id)
	return pc
}

// SetNillableNodeProcessID sets the "node_process" edge to the Node entity by ID if the given value is not nil.
func (pc *ProcesCreate) SetNillableNodeProcessID(id *uint) *ProcesCreate {
	if id != nil {
		pc = pc.SetNodeProcessID(*id)
	}
	return pc
}

// SetNodeProcess sets the "node_process" edge to the Node entity.
func (pc *ProcesCreate) SetNodeProcess(n *Node) *ProcesCreate {
	return pc.SetNodeProcessID(n.ID)
}

// SetContainerProcessID sets the "container_process" edge to the Container entity by ID.
func (pc *ProcesCreate) SetContainerProcessID(id uint) *ProcesCreate {
	pc.mutation.SetContainerProcessID(id)
	return pc
}

// SetNillableContainerProcessID sets the "container_process" edge to the Container entity by ID if the given value is not nil.
func (pc *ProcesCreate) SetNillableContainerProcessID(id *uint) *ProcesCreate {
	if id != nil {
		pc = pc.SetContainerProcessID(*id)
	}
	return pc
}

// SetContainerProcess sets the "container_process" edge to the Container entity.
func (pc *ProcesCreate) SetContainerProcess(c *Container) *ProcesCreate {
	return pc.SetContainerProcessID(c.ID)
}

// Mutation returns the ProcesMutation object of the builder.
func (pc *ProcesCreate) Mutation() *ProcesMutation {
	return pc.mutation
}

// Save creates the Proces in the database.
func (pc *ProcesCreate) Save(ctx context.Context) (*Proces, error) {
	var (
		err  error
		node *Proces
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProcesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *ProcesCreate) SaveX(ctx context.Context) *Proces {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *ProcesCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *ProcesCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *ProcesCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := proces.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := proces.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.DeletedAt(); !ok {
		v := proces.DefaultDeletedAt()
		pc.mutation.SetDeletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *ProcesCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	if _, ok := pc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "deleted_at"`)}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if _, ok := pc.mutation.PId(); !ok {
		return &ValidationError{Name: "pId", err: errors.New(`ent: missing required field "pId"`)}
	}
	if _, ok := pc.mutation.Cmd(); !ok {
		return &ValidationError{Name: "cmd", err: errors.New(`ent: missing required field "cmd"`)}
	}
	if _, ok := pc.mutation.Info(); !ok {
		return &ValidationError{Name: "info", err: errors.New(`ent: missing required field "info"`)}
	}
	if _, ok := pc.mutation.ClusterId(); !ok {
		return &ValidationError{Name: "clusterId", err: errors.New(`ent: missing required field "clusterId"`)}
	}
	if _, ok := pc.mutation.NodeId(); !ok {
		return &ValidationError{Name: "nodeId", err: errors.New(`ent: missing required field "nodeId"`)}
	}
	if _, ok := pc.mutation.ContainerId(); !ok {
		return &ValidationError{Name: "containerId", err: errors.New(`ent: missing required field "containerId"`)}
	}
	return nil
}

func (pc *ProcesCreate) sqlSave(ctx context.Context) (*Proces, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	return _node, nil
}

func (pc *ProcesCreate) createSpec() (*Proces, *sqlgraph.CreateSpec) {
	var (
		_node = &Proces{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: proces.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint,
				Column: proces.FieldID,
			},
		}
	)
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: proces.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: proces.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: proces.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: proces.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pc.mutation.PId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: proces.FieldPId,
		})
		_node.PId = value
	}
	if value, ok := pc.mutation.Cmd(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: proces.FieldCmd,
		})
		_node.Cmd = value
	}
	if value, ok := pc.mutation.Info(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: proces.FieldInfo,
		})
		_node.Info = value
	}
	if value, ok := pc.mutation.ClusterId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: proces.FieldClusterId,
		})
		_node.ClusterId = value
	}
	if value, ok := pc.mutation.NodeId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: proces.FieldNodeId,
		})
		_node.NodeId = value
	}
	if value, ok := pc.mutation.ContainerId(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: proces.FieldContainerId,
		})
		_node.ContainerId = value
	}
	if nodes := pc.mutation.NodeProcessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proces.NodeProcessTable,
			Columns: []string{proces.NodeProcessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint,
					Column: node.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.node_process = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pc.mutation.ContainerProcessIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proces.ContainerProcessTable,
			Columns: []string{proces.ContainerProcessColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint,
					Column: container.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.container_process = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProcesCreateBulk is the builder for creating many Proces entities in bulk.
type ProcesCreateBulk struct {
	config
	builders []*ProcesCreate
}

// Save creates the Proces entities in the database.
func (pcb *ProcesCreateBulk) Save(ctx context.Context) ([]*Proces, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Proces, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *ProcesCreateBulk) SaveX(ctx context.Context) []*Proces {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *ProcesCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *ProcesCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
