// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/agent"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/cluster"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/container"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/event"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/incidentbasicrule"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8scluster"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sconnector"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8scontainer"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sdaemonset"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sdeployment"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sevent"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8slabel"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8smetric"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8snamespace"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8snode"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sobject"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sobjecttag"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8spod"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sreplicaset"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/k8sstatefulset"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metric"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metricendpoint"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metriclabel"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metricname"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/metrictype"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/node"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/proces"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/schema"
	"github.com/willie-lin/kubeMonitor/pkg/nextserver/database/ent/setting"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentMixin := schema.Agent{}.Mixin()
	agentMixinFields0 := agentMixin[0].Fields()
	_ = agentMixinFields0
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentMixinFields0[0].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentMixinFields0[1].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescDeletedAt is the schema descriptor for deleted_at field.
	agentDescDeletedAt := agentMixinFields0[2].Descriptor()
	// agent.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	agent.DefaultDeletedAt = agentDescDeletedAt.Default.(func() time.Time)
	// agent.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	agent.UpdateDefaultDeletedAt = agentDescDeletedAt.UpdateDefault.(func() time.Time)
	// agentDescVersion is the schema descriptor for version field.
	agentDescVersion := agentFields[2].Descriptor()
	// agent.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	agent.VersionValidator = agentDescVersion.Validators[0].(func(string) error)
	// agentDescIpv4 is the schema descriptor for ipv4 field.
	agentDescIpv4 := agentFields[3].Descriptor()
	// agent.Ipv4Validator is a validator for the "ipv4" field. It is called by the builders before save.
	agent.Ipv4Validator = agentDescIpv4.Validators[0].(func(string) error)
	// agentDescIpv6 is the schema descriptor for ipv6 field.
	agentDescIpv6 := agentFields[4].Descriptor()
	// agent.Ipv6Validator is a validator for the "ipv6" field. It is called by the builders before save.
	agent.Ipv6Validator = agentDescIpv6.Validators[0].(func(string) error)
	// agentDescPublicIpv4 is the schema descriptor for public_ipv4 field.
	agentDescPublicIpv4 := agentFields[5].Descriptor()
	// agent.PublicIpv4Validator is a validator for the "public_ipv4" field. It is called by the builders before save.
	agent.PublicIpv4Validator = agentDescPublicIpv4.Validators[0].(func(string) error)
	// agentDescPublicIpv6 is the schema descriptor for public_ipv6 field.
	agentDescPublicIpv6 := agentFields[6].Descriptor()
	// agent.PublicIpv6Validator is a validator for the "public_ipv6" field. It is called by the builders before save.
	agent.PublicIpv6Validator = agentDescPublicIpv6.Validators[0].(func(string) error)
	// agentDescLastContact is the schema descriptor for last_contact field.
	agentDescLastContact := agentFields[7].Descriptor()
	// agent.DefaultLastContact holds the default value on creation for the last_contact field.
	agent.DefaultLastContact = agentDescLastContact.Default.(func() time.Time)
	// agentDescUUID is the schema descriptor for uuid field.
	agentDescUUID := agentFields[9].Descriptor()
	// agent.UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	agent.UUIDValidator = agentDescUUID.Validators[0].(func(string) error)
	// agentDescMachineId is the schema descriptor for machineId field.
	agentDescMachineId := agentFields[10].Descriptor()
	// agent.MachineIdValidator is a validator for the "machineId" field. It is called by the builders before save.
	agent.MachineIdValidator = agentDescMachineId.Validators[0].(func(string) error)
	clusterMixin := schema.Cluster{}.Mixin()
	clusterMixinFields0 := clusterMixin[0].Fields()
	_ = clusterMixinFields0
	clusterFields := schema.Cluster{}.Fields()
	_ = clusterFields
	// clusterDescCreatedAt is the schema descriptor for created_at field.
	clusterDescCreatedAt := clusterMixinFields0[0].Descriptor()
	// cluster.DefaultCreatedAt holds the default value on creation for the created_at field.
	cluster.DefaultCreatedAt = clusterDescCreatedAt.Default.(func() time.Time)
	// clusterDescUpdatedAt is the schema descriptor for updated_at field.
	clusterDescUpdatedAt := clusterMixinFields0[1].Descriptor()
	// cluster.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cluster.DefaultUpdatedAt = clusterDescUpdatedAt.Default.(func() time.Time)
	// cluster.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cluster.UpdateDefaultUpdatedAt = clusterDescUpdatedAt.UpdateDefault.(func() time.Time)
	// clusterDescDeletedAt is the schema descriptor for deleted_at field.
	clusterDescDeletedAt := clusterMixinFields0[2].Descriptor()
	// cluster.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	cluster.DefaultDeletedAt = clusterDescDeletedAt.Default.(func() time.Time)
	// cluster.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	cluster.UpdateDefaultDeletedAt = clusterDescDeletedAt.UpdateDefault.(func() time.Time)
	// clusterDescName is the schema descriptor for name field.
	clusterDescName := clusterFields[1].Descriptor()
	// cluster.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cluster.NameValidator = clusterDescName.Validators[0].(func(string) error)
	containerMixin := schema.Container{}.Mixin()
	containerMixinFields0 := containerMixin[0].Fields()
	_ = containerMixinFields0
	containerFields := schema.Container{}.Fields()
	_ = containerFields
	// containerDescCreatedAt is the schema descriptor for created_at field.
	containerDescCreatedAt := containerMixinFields0[0].Descriptor()
	// container.DefaultCreatedAt holds the default value on creation for the created_at field.
	container.DefaultCreatedAt = containerDescCreatedAt.Default.(func() time.Time)
	// containerDescUpdatedAt is the schema descriptor for updated_at field.
	containerDescUpdatedAt := containerMixinFields0[1].Descriptor()
	// container.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	container.DefaultUpdatedAt = containerDescUpdatedAt.Default.(func() time.Time)
	// container.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	container.UpdateDefaultUpdatedAt = containerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// containerDescDeletedAt is the schema descriptor for deleted_at field.
	containerDescDeletedAt := containerMixinFields0[2].Descriptor()
	// container.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	container.DefaultDeletedAt = containerDescDeletedAt.Default.(func() time.Time)
	// container.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	container.UpdateDefaultDeletedAt = containerDescDeletedAt.UpdateDefault.(func() time.Time)
	// containerDescContainerId is the schema descriptor for containerId field.
	containerDescContainerId := containerFields[2].Descriptor()
	// container.ContainerIdValidator is a validator for the "containerId" field. It is called by the builders before save.
	container.ContainerIdValidator = containerDescContainerId.Validators[0].(func(string) error)
	// containerDescName is the schema descriptor for name field.
	containerDescName := containerFields[3].Descriptor()
	// container.NameValidator is a validator for the "name" field. It is called by the builders before save.
	container.NameValidator = containerDescName.Validators[0].(func(string) error)
	// containerDescImage is the schema descriptor for image field.
	containerDescImage := containerFields[4].Descriptor()
	// container.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	container.ImageValidator = containerDescImage.Validators[0].(func(string) error)
	eventMixin := schema.Event{}.Mixin()
	eventMixinFields0 := eventMixin[0].Fields()
	_ = eventMixinFields0
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventMixinFields0[0].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() time.Time)
	// eventDescUpdatedAt is the schema descriptor for updated_at field.
	eventDescUpdatedAt := eventMixinFields0[1].Descriptor()
	// event.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	event.DefaultUpdatedAt = eventDescUpdatedAt.Default.(func() time.Time)
	// event.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	event.UpdateDefaultUpdatedAt = eventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// eventDescDeletedAt is the schema descriptor for deleted_at field.
	eventDescDeletedAt := eventMixinFields0[2].Descriptor()
	// event.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	event.DefaultDeletedAt = eventDescDeletedAt.Default.(func() time.Time)
	// event.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	event.UpdateDefaultDeletedAt = eventDescDeletedAt.UpdateDefault.(func() time.Time)
	incidentbasicruleMixin := schema.IncidentBasicRule{}.Mixin()
	incidentbasicruleMixinFields0 := incidentbasicruleMixin[0].Fields()
	_ = incidentbasicruleMixinFields0
	incidentbasicruleFields := schema.IncidentBasicRule{}.Fields()
	_ = incidentbasicruleFields
	// incidentbasicruleDescCreatedAt is the schema descriptor for created_at field.
	incidentbasicruleDescCreatedAt := incidentbasicruleMixinFields0[0].Descriptor()
	// incidentbasicrule.DefaultCreatedAt holds the default value on creation for the created_at field.
	incidentbasicrule.DefaultCreatedAt = incidentbasicruleDescCreatedAt.Default.(func() time.Time)
	// incidentbasicruleDescUpdatedAt is the schema descriptor for updated_at field.
	incidentbasicruleDescUpdatedAt := incidentbasicruleMixinFields0[1].Descriptor()
	// incidentbasicrule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	incidentbasicrule.DefaultUpdatedAt = incidentbasicruleDescUpdatedAt.Default.(func() time.Time)
	// incidentbasicrule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	incidentbasicrule.UpdateDefaultUpdatedAt = incidentbasicruleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// incidentbasicruleDescDeletedAt is the schema descriptor for deleted_at field.
	incidentbasicruleDescDeletedAt := incidentbasicruleMixinFields0[2].Descriptor()
	// incidentbasicrule.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	incidentbasicrule.DefaultDeletedAt = incidentbasicruleDescDeletedAt.Default.(func() time.Time)
	// incidentbasicrule.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	incidentbasicrule.UpdateDefaultDeletedAt = incidentbasicruleDescDeletedAt.UpdateDefault.(func() time.Time)
	k8sclusterMixin := schema.K8sCluster{}.Mixin()
	k8sclusterMixinFields0 := k8sclusterMixin[0].Fields()
	_ = k8sclusterMixinFields0
	k8sclusterFields := schema.K8sCluster{}.Fields()
	_ = k8sclusterFields
	// k8sclusterDescCreatedAt is the schema descriptor for created_at field.
	k8sclusterDescCreatedAt := k8sclusterMixinFields0[0].Descriptor()
	// k8scluster.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8scluster.DefaultCreatedAt = k8sclusterDescCreatedAt.Default.(func() time.Time)
	// k8sclusterDescUpdatedAt is the schema descriptor for updated_at field.
	k8sclusterDescUpdatedAt := k8sclusterMixinFields0[1].Descriptor()
	// k8scluster.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8scluster.DefaultUpdatedAt = k8sclusterDescUpdatedAt.Default.(func() time.Time)
	// k8scluster.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8scluster.UpdateDefaultUpdatedAt = k8sclusterDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sclusterDescDeletedAt is the schema descriptor for deleted_at field.
	k8sclusterDescDeletedAt := k8sclusterMixinFields0[2].Descriptor()
	// k8scluster.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8scluster.DefaultDeletedAt = k8sclusterDescDeletedAt.Default.(func() time.Time)
	// k8scluster.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8scluster.UpdateDefaultDeletedAt = k8sclusterDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sclusterDescName is the schema descriptor for name field.
	k8sclusterDescName := k8sclusterFields[1].Descriptor()
	// k8scluster.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8scluster.NameValidator = k8sclusterDescName.Validators[0].(func(string) error)
	k8sconnectorMixin := schema.K8sConnector{}.Mixin()
	k8sconnectorMixinFields0 := k8sconnectorMixin[0].Fields()
	_ = k8sconnectorMixinFields0
	k8sconnectorFields := schema.K8sConnector{}.Fields()
	_ = k8sconnectorFields
	// k8sconnectorDescCreatedAt is the schema descriptor for created_at field.
	k8sconnectorDescCreatedAt := k8sconnectorMixinFields0[0].Descriptor()
	// k8sconnector.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sconnector.DefaultCreatedAt = k8sconnectorDescCreatedAt.Default.(func() time.Time)
	// k8sconnectorDescUpdatedAt is the schema descriptor for updated_at field.
	k8sconnectorDescUpdatedAt := k8sconnectorMixinFields0[1].Descriptor()
	// k8sconnector.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sconnector.DefaultUpdatedAt = k8sconnectorDescUpdatedAt.Default.(func() time.Time)
	// k8sconnector.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sconnector.UpdateDefaultUpdatedAt = k8sconnectorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sconnectorDescDeletedAt is the schema descriptor for deleted_at field.
	k8sconnectorDescDeletedAt := k8sconnectorMixinFields0[2].Descriptor()
	// k8sconnector.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sconnector.DefaultDeletedAt = k8sconnectorDescDeletedAt.Default.(func() time.Time)
	// k8sconnector.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sconnector.UpdateDefaultDeletedAt = k8sconnectorDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sconnectorDescName is the schema descriptor for name field.
	k8sconnectorDescName := k8sconnectorFields[1].Descriptor()
	// k8sconnector.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sconnector.NameValidator = k8sconnectorDescName.Validators[0].(func(string) error)
	// k8sconnectorDescStatus is the schema descriptor for status field.
	k8sconnectorDescStatus := k8sconnectorFields[2].Descriptor()
	// k8sconnector.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	k8sconnector.StatusValidator = k8sconnectorDescStatus.Validators[0].(func(string) error)
	// k8sconnectorDescMethod is the schema descriptor for method field.
	k8sconnectorDescMethod := k8sconnectorFields[3].Descriptor()
	// k8sconnector.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	k8sconnector.MethodValidator = k8sconnectorDescMethod.Validators[0].(func(string) error)
	k8scontainerMixin := schema.K8sContainer{}.Mixin()
	k8scontainerMixinFields0 := k8scontainerMixin[0].Fields()
	_ = k8scontainerMixinFields0
	k8scontainerFields := schema.K8sContainer{}.Fields()
	_ = k8scontainerFields
	// k8scontainerDescCreatedAt is the schema descriptor for created_at field.
	k8scontainerDescCreatedAt := k8scontainerMixinFields0[0].Descriptor()
	// k8scontainer.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8scontainer.DefaultCreatedAt = k8scontainerDescCreatedAt.Default.(func() time.Time)
	// k8scontainerDescUpdatedAt is the schema descriptor for updated_at field.
	k8scontainerDescUpdatedAt := k8scontainerMixinFields0[1].Descriptor()
	// k8scontainer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8scontainer.DefaultUpdatedAt = k8scontainerDescUpdatedAt.Default.(func() time.Time)
	// k8scontainer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8scontainer.UpdateDefaultUpdatedAt = k8scontainerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8scontainerDescDeletedAt is the schema descriptor for deleted_at field.
	k8scontainerDescDeletedAt := k8scontainerMixinFields0[2].Descriptor()
	// k8scontainer.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8scontainer.DefaultDeletedAt = k8scontainerDescDeletedAt.Default.(func() time.Time)
	// k8scontainer.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8scontainer.UpdateDefaultDeletedAt = k8scontainerDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8scontainerDescName is the schema descriptor for name field.
	k8scontainerDescName := k8scontainerFields[1].Descriptor()
	// k8scontainer.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8scontainer.NameValidator = k8scontainerDescName.Validators[0].(func(string) error)
	// k8scontainerDescImage is the schema descriptor for image field.
	k8scontainerDescImage := k8scontainerFields[2].Descriptor()
	// k8scontainer.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	k8scontainer.ImageValidator = k8scontainerDescImage.Validators[0].(func(string) error)
	// k8scontainerDescContainerType is the schema descriptor for containerType field.
	k8scontainerDescContainerType := k8scontainerFields[3].Descriptor()
	// k8scontainer.ContainerTypeValidator is a validator for the "containerType" field. It is called by the builders before save.
	k8scontainer.ContainerTypeValidator = k8scontainerDescContainerType.Validators[0].(func(string) error)
	// k8scontainerDescContainerId is the schema descriptor for containerId field.
	k8scontainerDescContainerId := k8scontainerFields[4].Descriptor()
	// k8scontainer.ContainerIdValidator is a validator for the "containerId" field. It is called by the builders before save.
	k8scontainer.ContainerIdValidator = k8scontainerDescContainerId.Validators[0].(func(string) error)
	k8sdaemonsetMixin := schema.K8sDaemonSet{}.Mixin()
	k8sdaemonsetMixinFields0 := k8sdaemonsetMixin[0].Fields()
	_ = k8sdaemonsetMixinFields0
	k8sdaemonsetFields := schema.K8sDaemonSet{}.Fields()
	_ = k8sdaemonsetFields
	// k8sdaemonsetDescCreatedAt is the schema descriptor for created_at field.
	k8sdaemonsetDescCreatedAt := k8sdaemonsetMixinFields0[0].Descriptor()
	// k8sdaemonset.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sdaemonset.DefaultCreatedAt = k8sdaemonsetDescCreatedAt.Default.(func() time.Time)
	// k8sdaemonsetDescUpdatedAt is the schema descriptor for updated_at field.
	k8sdaemonsetDescUpdatedAt := k8sdaemonsetMixinFields0[1].Descriptor()
	// k8sdaemonset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sdaemonset.DefaultUpdatedAt = k8sdaemonsetDescUpdatedAt.Default.(func() time.Time)
	// k8sdaemonset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sdaemonset.UpdateDefaultUpdatedAt = k8sdaemonsetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sdaemonsetDescDeletedAt is the schema descriptor for deleted_at field.
	k8sdaemonsetDescDeletedAt := k8sdaemonsetMixinFields0[2].Descriptor()
	// k8sdaemonset.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sdaemonset.DefaultDeletedAt = k8sdaemonsetDescDeletedAt.Default.(func() time.Time)
	// k8sdaemonset.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sdaemonset.UpdateDefaultDeletedAt = k8sdaemonsetDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sdaemonsetDescName is the schema descriptor for name field.
	k8sdaemonsetDescName := k8sdaemonsetFields[1].Descriptor()
	// k8sdaemonset.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sdaemonset.NameValidator = k8sdaemonsetDescName.Validators[0].(func(string) error)
	k8sdeploymentMixin := schema.K8sDeployment{}.Mixin()
	k8sdeploymentMixinFields0 := k8sdeploymentMixin[0].Fields()
	_ = k8sdeploymentMixinFields0
	k8sdeploymentFields := schema.K8sDeployment{}.Fields()
	_ = k8sdeploymentFields
	// k8sdeploymentDescCreatedAt is the schema descriptor for created_at field.
	k8sdeploymentDescCreatedAt := k8sdeploymentMixinFields0[0].Descriptor()
	// k8sdeployment.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sdeployment.DefaultCreatedAt = k8sdeploymentDescCreatedAt.Default.(func() time.Time)
	// k8sdeploymentDescUpdatedAt is the schema descriptor for updated_at field.
	k8sdeploymentDescUpdatedAt := k8sdeploymentMixinFields0[1].Descriptor()
	// k8sdeployment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sdeployment.DefaultUpdatedAt = k8sdeploymentDescUpdatedAt.Default.(func() time.Time)
	// k8sdeployment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sdeployment.UpdateDefaultUpdatedAt = k8sdeploymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sdeploymentDescDeletedAt is the schema descriptor for deleted_at field.
	k8sdeploymentDescDeletedAt := k8sdeploymentMixinFields0[2].Descriptor()
	// k8sdeployment.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sdeployment.DefaultDeletedAt = k8sdeploymentDescDeletedAt.Default.(func() time.Time)
	// k8sdeployment.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sdeployment.UpdateDefaultDeletedAt = k8sdeploymentDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sdeploymentDescName is the schema descriptor for name field.
	k8sdeploymentDescName := k8sdeploymentFields[1].Descriptor()
	// k8sdeployment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sdeployment.NameValidator = k8sdeploymentDescName.Validators[0].(func(string) error)
	k8seventMixin := schema.K8sEvent{}.Mixin()
	k8seventMixinFields0 := k8seventMixin[0].Fields()
	_ = k8seventMixinFields0
	k8seventFields := schema.K8sEvent{}.Fields()
	_ = k8seventFields
	// k8seventDescCreatedAt is the schema descriptor for created_at field.
	k8seventDescCreatedAt := k8seventMixinFields0[0].Descriptor()
	// k8sevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sevent.DefaultCreatedAt = k8seventDescCreatedAt.Default.(func() time.Time)
	// k8seventDescUpdatedAt is the schema descriptor for updated_at field.
	k8seventDescUpdatedAt := k8seventMixinFields0[1].Descriptor()
	// k8sevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sevent.DefaultUpdatedAt = k8seventDescUpdatedAt.Default.(func() time.Time)
	// k8sevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sevent.UpdateDefaultUpdatedAt = k8seventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8seventDescDeletedAt is the schema descriptor for deleted_at field.
	k8seventDescDeletedAt := k8seventMixinFields0[2].Descriptor()
	// k8sevent.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sevent.DefaultDeletedAt = k8seventDescDeletedAt.Default.(func() time.Time)
	// k8sevent.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sevent.UpdateDefaultDeletedAt = k8seventDescDeletedAt.UpdateDefault.(func() time.Time)
	k8slabelMixin := schema.K8sLabel{}.Mixin()
	k8slabelMixinFields0 := k8slabelMixin[0].Fields()
	_ = k8slabelMixinFields0
	k8slabelFields := schema.K8sLabel{}.Fields()
	_ = k8slabelFields
	// k8slabelDescCreatedAt is the schema descriptor for created_at field.
	k8slabelDescCreatedAt := k8slabelMixinFields0[0].Descriptor()
	// k8slabel.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8slabel.DefaultCreatedAt = k8slabelDescCreatedAt.Default.(func() time.Time)
	// k8slabelDescUpdatedAt is the schema descriptor for updated_at field.
	k8slabelDescUpdatedAt := k8slabelMixinFields0[1].Descriptor()
	// k8slabel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8slabel.DefaultUpdatedAt = k8slabelDescUpdatedAt.Default.(func() time.Time)
	// k8slabel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8slabel.UpdateDefaultUpdatedAt = k8slabelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8slabelDescDeletedAt is the schema descriptor for deleted_at field.
	k8slabelDescDeletedAt := k8slabelMixinFields0[2].Descriptor()
	// k8slabel.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8slabel.DefaultDeletedAt = k8slabelDescDeletedAt.Default.(func() time.Time)
	// k8slabel.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8slabel.UpdateDefaultDeletedAt = k8slabelDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8slabelDescLabel is the schema descriptor for label field.
	k8slabelDescLabel := k8slabelFields[1].Descriptor()
	// k8slabel.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	k8slabel.LabelValidator = k8slabelDescLabel.Validators[0].(func(string) error)
	k8smetricMixin := schema.K8sMetric{}.Mixin()
	k8smetricMixinFields0 := k8smetricMixin[0].Fields()
	_ = k8smetricMixinFields0
	k8smetricFields := schema.K8sMetric{}.Fields()
	_ = k8smetricFields
	// k8smetricDescCreatedAt is the schema descriptor for created_at field.
	k8smetricDescCreatedAt := k8smetricMixinFields0[0].Descriptor()
	// k8smetric.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8smetric.DefaultCreatedAt = k8smetricDescCreatedAt.Default.(func() time.Time)
	// k8smetricDescUpdatedAt is the schema descriptor for updated_at field.
	k8smetricDescUpdatedAt := k8smetricMixinFields0[1].Descriptor()
	// k8smetric.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8smetric.DefaultUpdatedAt = k8smetricDescUpdatedAt.Default.(func() time.Time)
	// k8smetric.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8smetric.UpdateDefaultUpdatedAt = k8smetricDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8smetricDescDeletedAt is the schema descriptor for deleted_at field.
	k8smetricDescDeletedAt := k8smetricMixinFields0[2].Descriptor()
	// k8smetric.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8smetric.DefaultDeletedAt = k8smetricDescDeletedAt.Default.(func() time.Time)
	// k8smetric.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8smetric.UpdateDefaultDeletedAt = k8smetricDescDeletedAt.UpdateDefault.(func() time.Time)
	k8snamespaceMixin := schema.K8sNamespace{}.Mixin()
	k8snamespaceMixinFields0 := k8snamespaceMixin[0].Fields()
	_ = k8snamespaceMixinFields0
	k8snamespaceFields := schema.K8sNamespace{}.Fields()
	_ = k8snamespaceFields
	// k8snamespaceDescCreatedAt is the schema descriptor for created_at field.
	k8snamespaceDescCreatedAt := k8snamespaceMixinFields0[0].Descriptor()
	// k8snamespace.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8snamespace.DefaultCreatedAt = k8snamespaceDescCreatedAt.Default.(func() time.Time)
	// k8snamespaceDescUpdatedAt is the schema descriptor for updated_at field.
	k8snamespaceDescUpdatedAt := k8snamespaceMixinFields0[1].Descriptor()
	// k8snamespace.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8snamespace.DefaultUpdatedAt = k8snamespaceDescUpdatedAt.Default.(func() time.Time)
	// k8snamespace.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8snamespace.UpdateDefaultUpdatedAt = k8snamespaceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8snamespaceDescDeletedAt is the schema descriptor for deleted_at field.
	k8snamespaceDescDeletedAt := k8snamespaceMixinFields0[2].Descriptor()
	// k8snamespace.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8snamespace.DefaultDeletedAt = k8snamespaceDescDeletedAt.Default.(func() time.Time)
	// k8snamespace.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8snamespace.UpdateDefaultDeletedAt = k8snamespaceDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8snamespaceDescName is the schema descriptor for name field.
	k8snamespaceDescName := k8snamespaceFields[1].Descriptor()
	// k8snamespace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8snamespace.NameValidator = k8snamespaceDescName.Validators[0].(func(string) error)
	k8snodeMixin := schema.K8sNode{}.Mixin()
	k8snodeMixinFields0 := k8snodeMixin[0].Fields()
	_ = k8snodeMixinFields0
	k8snodeFields := schema.K8sNode{}.Fields()
	_ = k8snodeFields
	// k8snodeDescCreatedAt is the schema descriptor for created_at field.
	k8snodeDescCreatedAt := k8snodeMixinFields0[0].Descriptor()
	// k8snode.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8snode.DefaultCreatedAt = k8snodeDescCreatedAt.Default.(func() time.Time)
	// k8snodeDescUpdatedAt is the schema descriptor for updated_at field.
	k8snodeDescUpdatedAt := k8snodeMixinFields0[1].Descriptor()
	// k8snode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8snode.DefaultUpdatedAt = k8snodeDescUpdatedAt.Default.(func() time.Time)
	// k8snode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8snode.UpdateDefaultUpdatedAt = k8snodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8snodeDescDeletedAt is the schema descriptor for deleted_at field.
	k8snodeDescDeletedAt := k8snodeMixinFields0[2].Descriptor()
	// k8snode.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8snode.DefaultDeletedAt = k8snodeDescDeletedAt.Default.(func() time.Time)
	// k8snode.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8snode.UpdateDefaultDeletedAt = k8snodeDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8snodeDescName is the schema descriptor for name field.
	k8snodeDescName := k8snodeFields[1].Descriptor()
	// k8snode.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8snode.NameValidator = k8snodeDescName.Validators[0].(func(string) error)
	k8sobjectMixin := schema.K8sObject{}.Mixin()
	k8sobjectMixinFields0 := k8sobjectMixin[0].Fields()
	_ = k8sobjectMixinFields0
	k8sobjectFields := schema.K8sObject{}.Fields()
	_ = k8sobjectFields
	// k8sobjectDescCreatedAt is the schema descriptor for created_at field.
	k8sobjectDescCreatedAt := k8sobjectMixinFields0[0].Descriptor()
	// k8sobject.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sobject.DefaultCreatedAt = k8sobjectDescCreatedAt.Default.(func() time.Time)
	// k8sobjectDescUpdatedAt is the schema descriptor for updated_at field.
	k8sobjectDescUpdatedAt := k8sobjectMixinFields0[1].Descriptor()
	// k8sobject.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sobject.DefaultUpdatedAt = k8sobjectDescUpdatedAt.Default.(func() time.Time)
	// k8sobject.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sobject.UpdateDefaultUpdatedAt = k8sobjectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sobjectDescDeletedAt is the schema descriptor for deleted_at field.
	k8sobjectDescDeletedAt := k8sobjectMixinFields0[2].Descriptor()
	// k8sobject.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sobject.DefaultDeletedAt = k8sobjectDescDeletedAt.Default.(func() time.Time)
	// k8sobject.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sobject.UpdateDefaultDeletedAt = k8sobjectDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sobjectDescApiVersion is the schema descriptor for apiVersion field.
	k8sobjectDescApiVersion := k8sobjectFields[2].Descriptor()
	// k8sobject.ApiVersionValidator is a validator for the "apiVersion" field. It is called by the builders before save.
	k8sobject.ApiVersionValidator = k8sobjectDescApiVersion.Validators[0].(func(string) error)
	// k8sobjectDescKind is the schema descriptor for kind field.
	k8sobjectDescKind := k8sobjectFields[3].Descriptor()
	// k8sobject.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	k8sobject.KindValidator = k8sobjectDescKind.Validators[0].(func(string) error)
	// k8sobjectDescName is the schema descriptor for name field.
	k8sobjectDescName := k8sobjectFields[4].Descriptor()
	// k8sobject.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sobject.NameValidator = k8sobjectDescName.Validators[0].(func(string) error)
	k8sobjecttagMixin := schema.K8sObjectTag{}.Mixin()
	k8sobjecttagMixinFields0 := k8sobjecttagMixin[0].Fields()
	_ = k8sobjecttagMixinFields0
	k8sobjecttagFields := schema.K8sObjectTag{}.Fields()
	_ = k8sobjecttagFields
	// k8sobjecttagDescCreatedAt is the schema descriptor for created_at field.
	k8sobjecttagDescCreatedAt := k8sobjecttagMixinFields0[0].Descriptor()
	// k8sobjecttag.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sobjecttag.DefaultCreatedAt = k8sobjecttagDescCreatedAt.Default.(func() time.Time)
	// k8sobjecttagDescUpdatedAt is the schema descriptor for updated_at field.
	k8sobjecttagDescUpdatedAt := k8sobjecttagMixinFields0[1].Descriptor()
	// k8sobjecttag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sobjecttag.DefaultUpdatedAt = k8sobjecttagDescUpdatedAt.Default.(func() time.Time)
	// k8sobjecttag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sobjecttag.UpdateDefaultUpdatedAt = k8sobjecttagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sobjecttagDescDeletedAt is the schema descriptor for deleted_at field.
	k8sobjecttagDescDeletedAt := k8sobjecttagMixinFields0[2].Descriptor()
	// k8sobjecttag.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sobjecttag.DefaultDeletedAt = k8sobjecttagDescDeletedAt.Default.(func() time.Time)
	// k8sobjecttag.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sobjecttag.UpdateDefaultDeletedAt = k8sobjecttagDescDeletedAt.UpdateDefault.(func() time.Time)
	k8spodMixin := schema.K8sPod{}.Mixin()
	k8spodMixinFields0 := k8spodMixin[0].Fields()
	_ = k8spodMixinFields0
	k8spodFields := schema.K8sPod{}.Fields()
	_ = k8spodFields
	// k8spodDescCreatedAt is the schema descriptor for created_at field.
	k8spodDescCreatedAt := k8spodMixinFields0[0].Descriptor()
	// k8spod.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8spod.DefaultCreatedAt = k8spodDescCreatedAt.Default.(func() time.Time)
	// k8spodDescUpdatedAt is the schema descriptor for updated_at field.
	k8spodDescUpdatedAt := k8spodMixinFields0[1].Descriptor()
	// k8spod.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8spod.DefaultUpdatedAt = k8spodDescUpdatedAt.Default.(func() time.Time)
	// k8spod.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8spod.UpdateDefaultUpdatedAt = k8spodDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8spodDescDeletedAt is the schema descriptor for deleted_at field.
	k8spodDescDeletedAt := k8spodMixinFields0[2].Descriptor()
	// k8spod.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8spod.DefaultDeletedAt = k8spodDescDeletedAt.Default.(func() time.Time)
	// k8spod.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8spod.UpdateDefaultDeletedAt = k8spodDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8spodDescName is the schema descriptor for name field.
	k8spodDescName := k8spodFields[1].Descriptor()
	// k8spod.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8spod.NameValidator = k8spodDescName.Validators[0].(func(string) error)
	// k8spodDescQos is the schema descriptor for qos field.
	k8spodDescQos := k8spodFields[2].Descriptor()
	// k8spod.QosValidator is a validator for the "qos" field. It is called by the builders before save.
	k8spod.QosValidator = k8spodDescQos.Validators[0].(func(string) error)
	k8sreplicasetMixin := schema.K8sReplicaSet{}.Mixin()
	k8sreplicasetMixinFields0 := k8sreplicasetMixin[0].Fields()
	_ = k8sreplicasetMixinFields0
	k8sreplicasetFields := schema.K8sReplicaSet{}.Fields()
	_ = k8sreplicasetFields
	// k8sreplicasetDescCreatedAt is the schema descriptor for created_at field.
	k8sreplicasetDescCreatedAt := k8sreplicasetMixinFields0[0].Descriptor()
	// k8sreplicaset.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sreplicaset.DefaultCreatedAt = k8sreplicasetDescCreatedAt.Default.(func() time.Time)
	// k8sreplicasetDescUpdatedAt is the schema descriptor for updated_at field.
	k8sreplicasetDescUpdatedAt := k8sreplicasetMixinFields0[1].Descriptor()
	// k8sreplicaset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sreplicaset.DefaultUpdatedAt = k8sreplicasetDescUpdatedAt.Default.(func() time.Time)
	// k8sreplicaset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sreplicaset.UpdateDefaultUpdatedAt = k8sreplicasetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sreplicasetDescDeletedAt is the schema descriptor for deleted_at field.
	k8sreplicasetDescDeletedAt := k8sreplicasetMixinFields0[2].Descriptor()
	// k8sreplicaset.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sreplicaset.DefaultDeletedAt = k8sreplicasetDescDeletedAt.Default.(func() time.Time)
	// k8sreplicaset.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sreplicaset.UpdateDefaultDeletedAt = k8sreplicasetDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sreplicasetDescName is the schema descriptor for name field.
	k8sreplicasetDescName := k8sreplicasetFields[1].Descriptor()
	// k8sreplicaset.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sreplicaset.NameValidator = k8sreplicasetDescName.Validators[0].(func(string) error)
	k8sstatefulsetMixin := schema.K8sStatefulSet{}.Mixin()
	k8sstatefulsetMixinFields0 := k8sstatefulsetMixin[0].Fields()
	_ = k8sstatefulsetMixinFields0
	k8sstatefulsetFields := schema.K8sStatefulSet{}.Fields()
	_ = k8sstatefulsetFields
	// k8sstatefulsetDescCreatedAt is the schema descriptor for created_at field.
	k8sstatefulsetDescCreatedAt := k8sstatefulsetMixinFields0[0].Descriptor()
	// k8sstatefulset.DefaultCreatedAt holds the default value on creation for the created_at field.
	k8sstatefulset.DefaultCreatedAt = k8sstatefulsetDescCreatedAt.Default.(func() time.Time)
	// k8sstatefulsetDescUpdatedAt is the schema descriptor for updated_at field.
	k8sstatefulsetDescUpdatedAt := k8sstatefulsetMixinFields0[1].Descriptor()
	// k8sstatefulset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	k8sstatefulset.DefaultUpdatedAt = k8sstatefulsetDescUpdatedAt.Default.(func() time.Time)
	// k8sstatefulset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	k8sstatefulset.UpdateDefaultUpdatedAt = k8sstatefulsetDescUpdatedAt.UpdateDefault.(func() time.Time)
	// k8sstatefulsetDescDeletedAt is the schema descriptor for deleted_at field.
	k8sstatefulsetDescDeletedAt := k8sstatefulsetMixinFields0[2].Descriptor()
	// k8sstatefulset.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	k8sstatefulset.DefaultDeletedAt = k8sstatefulsetDescDeletedAt.Default.(func() time.Time)
	// k8sstatefulset.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	k8sstatefulset.UpdateDefaultDeletedAt = k8sstatefulsetDescDeletedAt.UpdateDefault.(func() time.Time)
	// k8sstatefulsetDescName is the schema descriptor for name field.
	k8sstatefulsetDescName := k8sstatefulsetFields[1].Descriptor()
	// k8sstatefulset.NameValidator is a validator for the "name" field. It is called by the builders before save.
	k8sstatefulset.NameValidator = k8sstatefulsetDescName.Validators[0].(func(string) error)
	metricMixin := schema.Metric{}.Mixin()
	metricMixinFields0 := metricMixin[0].Fields()
	_ = metricMixinFields0
	metricFields := schema.Metric{}.Fields()
	_ = metricFields
	// metricDescCreatedAt is the schema descriptor for created_at field.
	metricDescCreatedAt := metricMixinFields0[0].Descriptor()
	// metric.DefaultCreatedAt holds the default value on creation for the created_at field.
	metric.DefaultCreatedAt = metricDescCreatedAt.Default.(func() time.Time)
	// metricDescUpdatedAt is the schema descriptor for updated_at field.
	metricDescUpdatedAt := metricMixinFields0[1].Descriptor()
	// metric.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metric.DefaultUpdatedAt = metricDescUpdatedAt.Default.(func() time.Time)
	// metric.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metric.UpdateDefaultUpdatedAt = metricDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metricDescDeletedAt is the schema descriptor for deleted_at field.
	metricDescDeletedAt := metricMixinFields0[2].Descriptor()
	// metric.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	metric.DefaultDeletedAt = metricDescDeletedAt.Default.(func() time.Time)
	// metric.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	metric.UpdateDefaultDeletedAt = metricDescDeletedAt.UpdateDefault.(func() time.Time)
	metricendpointMixin := schema.MetricEndpoint{}.Mixin()
	metricendpointMixinFields0 := metricendpointMixin[0].Fields()
	_ = metricendpointMixinFields0
	metricendpointFields := schema.MetricEndpoint{}.Fields()
	_ = metricendpointFields
	// metricendpointDescCreatedAt is the schema descriptor for created_at field.
	metricendpointDescCreatedAt := metricendpointMixinFields0[0].Descriptor()
	// metricendpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	metricendpoint.DefaultCreatedAt = metricendpointDescCreatedAt.Default.(func() time.Time)
	// metricendpointDescUpdatedAt is the schema descriptor for updated_at field.
	metricendpointDescUpdatedAt := metricendpointMixinFields0[1].Descriptor()
	// metricendpoint.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metricendpoint.DefaultUpdatedAt = metricendpointDescUpdatedAt.Default.(func() time.Time)
	// metricendpoint.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metricendpoint.UpdateDefaultUpdatedAt = metricendpointDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metricendpointDescDeletedAt is the schema descriptor for deleted_at field.
	metricendpointDescDeletedAt := metricendpointMixinFields0[2].Descriptor()
	// metricendpoint.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	metricendpoint.DefaultDeletedAt = metricendpointDescDeletedAt.Default.(func() time.Time)
	// metricendpoint.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	metricendpoint.UpdateDefaultDeletedAt = metricendpointDescDeletedAt.UpdateDefault.(func() time.Time)
	// metricendpointDescPath is the schema descriptor for path field.
	metricendpointDescPath := metricendpointFields[1].Descriptor()
	// metricendpoint.PathValidator is a validator for the "path" field. It is called by the builders before save.
	metricendpoint.PathValidator = metricendpointDescPath.Validators[0].(func(string) error)
	metriclabelMixin := schema.MetricLabel{}.Mixin()
	metriclabelMixinFields0 := metriclabelMixin[0].Fields()
	_ = metriclabelMixinFields0
	metriclabelFields := schema.MetricLabel{}.Fields()
	_ = metriclabelFields
	// metriclabelDescCreatedAt is the schema descriptor for created_at field.
	metriclabelDescCreatedAt := metriclabelMixinFields0[0].Descriptor()
	// metriclabel.DefaultCreatedAt holds the default value on creation for the created_at field.
	metriclabel.DefaultCreatedAt = metriclabelDescCreatedAt.Default.(func() time.Time)
	// metriclabelDescUpdatedAt is the schema descriptor for updated_at field.
	metriclabelDescUpdatedAt := metriclabelMixinFields0[1].Descriptor()
	// metriclabel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metriclabel.DefaultUpdatedAt = metriclabelDescUpdatedAt.Default.(func() time.Time)
	// metriclabel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metriclabel.UpdateDefaultUpdatedAt = metriclabelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metriclabelDescDeletedAt is the schema descriptor for deleted_at field.
	metriclabelDescDeletedAt := metriclabelMixinFields0[2].Descriptor()
	// metriclabel.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	metriclabel.DefaultDeletedAt = metriclabelDescDeletedAt.Default.(func() time.Time)
	// metriclabel.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	metriclabel.UpdateDefaultDeletedAt = metriclabelDescDeletedAt.UpdateDefault.(func() time.Time)
	// metriclabelDescLabel is the schema descriptor for label field.
	metriclabelDescLabel := metriclabelFields[1].Descriptor()
	// metriclabel.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	metriclabel.LabelValidator = metriclabelDescLabel.Validators[0].(func(string) error)
	metricnameMixin := schema.MetricName{}.Mixin()
	metricnameMixinFields0 := metricnameMixin[0].Fields()
	_ = metricnameMixinFields0
	metricnameFields := schema.MetricName{}.Fields()
	_ = metricnameFields
	// metricnameDescCreatedAt is the schema descriptor for created_at field.
	metricnameDescCreatedAt := metricnameMixinFields0[0].Descriptor()
	// metricname.DefaultCreatedAt holds the default value on creation for the created_at field.
	metricname.DefaultCreatedAt = metricnameDescCreatedAt.Default.(func() time.Time)
	// metricnameDescUpdatedAt is the schema descriptor for updated_at field.
	metricnameDescUpdatedAt := metricnameMixinFields0[1].Descriptor()
	// metricname.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metricname.DefaultUpdatedAt = metricnameDescUpdatedAt.Default.(func() time.Time)
	// metricname.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metricname.UpdateDefaultUpdatedAt = metricnameDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metricnameDescDeletedAt is the schema descriptor for deleted_at field.
	metricnameDescDeletedAt := metricnameMixinFields0[2].Descriptor()
	// metricname.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	metricname.DefaultDeletedAt = metricnameDescDeletedAt.Default.(func() time.Time)
	// metricname.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	metricname.UpdateDefaultDeletedAt = metricnameDescDeletedAt.UpdateDefault.(func() time.Time)
	// metricnameDescName is the schema descriptor for name field.
	metricnameDescName := metricnameFields[1].Descriptor()
	// metricname.NameValidator is a validator for the "name" field. It is called by the builders before save.
	metricname.NameValidator = metricnameDescName.Validators[0].(func(string) error)
	metrictypeMixin := schema.MetricType{}.Mixin()
	metrictypeMixinFields0 := metrictypeMixin[0].Fields()
	_ = metrictypeMixinFields0
	metrictypeFields := schema.MetricType{}.Fields()
	_ = metrictypeFields
	// metrictypeDescCreatedAt is the schema descriptor for created_at field.
	metrictypeDescCreatedAt := metrictypeMixinFields0[0].Descriptor()
	// metrictype.DefaultCreatedAt holds the default value on creation for the created_at field.
	metrictype.DefaultCreatedAt = metrictypeDescCreatedAt.Default.(func() time.Time)
	// metrictypeDescUpdatedAt is the schema descriptor for updated_at field.
	metrictypeDescUpdatedAt := metrictypeMixinFields0[1].Descriptor()
	// metrictype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	metrictype.DefaultUpdatedAt = metrictypeDescUpdatedAt.Default.(func() time.Time)
	// metrictype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	metrictype.UpdateDefaultUpdatedAt = metrictypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// metrictypeDescDeletedAt is the schema descriptor for deleted_at field.
	metrictypeDescDeletedAt := metrictypeMixinFields0[2].Descriptor()
	// metrictype.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	metrictype.DefaultDeletedAt = metrictypeDescDeletedAt.Default.(func() time.Time)
	// metrictype.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	metrictype.UpdateDefaultDeletedAt = metrictypeDescDeletedAt.UpdateDefault.(func() time.Time)
	nodeMixin := schema.Node{}.Mixin()
	nodeMixinFields0 := nodeMixin[0].Fields()
	_ = nodeMixinFields0
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeMixinFields0[0].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeMixinFields0[1].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescDeletedAt is the schema descriptor for deleted_at field.
	nodeDescDeletedAt := nodeMixinFields0[2].Descriptor()
	// node.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	node.DefaultDeletedAt = nodeDescDeletedAt.Default.(func() time.Time)
	// node.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	node.UpdateDefaultDeletedAt = nodeDescDeletedAt.UpdateDefault.(func() time.Time)
	// nodeDescHost is the schema descriptor for host field.
	nodeDescHost := nodeFields[1].Descriptor()
	// node.HostValidator is a validator for the "host" field. It is called by the builders before save.
	node.HostValidator = nodeDescHost.Validators[0].(func(string) error)
	// nodeDescIpv4 is the schema descriptor for ipv4 field.
	nodeDescIpv4 := nodeFields[2].Descriptor()
	// node.Ipv4Validator is a validator for the "ipv4" field. It is called by the builders before save.
	node.Ipv4Validator = nodeDescIpv4.Validators[0].(func(string) error)
	// nodeDescIpv6 is the schema descriptor for ipv6 field.
	nodeDescIpv6 := nodeFields[3].Descriptor()
	// node.Ipv6Validator is a validator for the "ipv6" field. It is called by the builders before save.
	node.Ipv6Validator = nodeDescIpv6.Validators[0].(func(string) error)
	// nodeDescPublicIpv4 is the schema descriptor for public_ipv4 field.
	nodeDescPublicIpv4 := nodeFields[4].Descriptor()
	// node.PublicIpv4Validator is a validator for the "public_ipv4" field. It is called by the builders before save.
	node.PublicIpv4Validator = nodeDescPublicIpv4.Validators[0].(func(string) error)
	// nodeDescPublicIpv6 is the schema descriptor for public_ipv6 field.
	nodeDescPublicIpv6 := nodeFields[5].Descriptor()
	// node.PublicIpv6Validator is a validator for the "public_ipv6" field. It is called by the builders before save.
	node.PublicIpv6Validator = nodeDescPublicIpv6.Validators[0].(func(string) error)
	// nodeDescOs is the schema descriptor for os field.
	nodeDescOs := nodeFields[6].Descriptor()
	// node.OsValidator is a validator for the "os" field. It is called by the builders before save.
	node.OsValidator = nodeDescOs.Validators[0].(func(string) error)
	// nodeDescPlatform is the schema descriptor for platform field.
	nodeDescPlatform := nodeFields[7].Descriptor()
	// node.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	node.PlatformValidator = nodeDescPlatform.Validators[0].(func(string) error)
	// nodeDescPlatformFamily is the schema descriptor for platformFamily field.
	nodeDescPlatformFamily := nodeFields[8].Descriptor()
	// node.PlatformFamilyValidator is a validator for the "platformFamily" field. It is called by the builders before save.
	node.PlatformFamilyValidator = nodeDescPlatformFamily.Validators[0].(func(string) error)
	procesMixin := schema.Proces{}.Mixin()
	procesMixinFields0 := procesMixin[0].Fields()
	_ = procesMixinFields0
	procesFields := schema.Proces{}.Fields()
	_ = procesFields
	// procesDescCreatedAt is the schema descriptor for created_at field.
	procesDescCreatedAt := procesMixinFields0[0].Descriptor()
	// proces.DefaultCreatedAt holds the default value on creation for the created_at field.
	proces.DefaultCreatedAt = procesDescCreatedAt.Default.(func() time.Time)
	// procesDescUpdatedAt is the schema descriptor for updated_at field.
	procesDescUpdatedAt := procesMixinFields0[1].Descriptor()
	// proces.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proces.DefaultUpdatedAt = procesDescUpdatedAt.Default.(func() time.Time)
	// proces.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proces.UpdateDefaultUpdatedAt = procesDescUpdatedAt.UpdateDefault.(func() time.Time)
	// procesDescDeletedAt is the schema descriptor for deleted_at field.
	procesDescDeletedAt := procesMixinFields0[2].Descriptor()
	// proces.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	proces.DefaultDeletedAt = procesDescDeletedAt.Default.(func() time.Time)
	// proces.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	proces.UpdateDefaultDeletedAt = procesDescDeletedAt.UpdateDefault.(func() time.Time)
	settingMixin := schema.Setting{}.Mixin()
	settingMixinFields0 := settingMixin[0].Fields()
	_ = settingMixinFields0
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingMixinFields0[0].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingMixinFields0[1].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// settingDescDeletedAt is the schema descriptor for deleted_at field.
	settingDescDeletedAt := settingMixinFields0[2].Descriptor()
	// setting.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	setting.DefaultDeletedAt = settingDescDeletedAt.Default.(func() time.Time)
	// setting.UpdateDefaultDeletedAt holds the default value on update for the deleted_at field.
	setting.UpdateDefaultDeletedAt = settingDescDeletedAt.UpdateDefault.(func() time.Time)
	// settingDescName is the schema descriptor for name field.
	settingDescName := settingFields[1].Descriptor()
	// setting.NameValidator is a validator for the "name" field. It is called by the builders before save.
	setting.NameValidator = settingDescName.Validators[0].(func(string) error)
}
