// Code generated by entc, DO NOT EDIT.

package agent

import (
	"time"
)

const (
	// Label holds the string label denoting the agent type in the database.
	Label = "agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOnline holds the string denoting the online field in the database.
	FieldOnline = "online"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldIpv4 holds the string denoting the ipv4 field in the database.
	FieldIpv4 = "ipv4"
	// FieldIpv6 holds the string denoting the ipv6 field in the database.
	FieldIpv6 = "ipv6"
	// FieldPublicIpv4 holds the string denoting the public_ipv4 field in the database.
	FieldPublicIpv4 = "public_ipv4"
	// FieldPublicIpv6 holds the string denoting the public_ipv6 field in the database.
	FieldPublicIpv6 = "public_ipv6"
	// FieldLastContact holds the string denoting the last_contact field in the database.
	FieldLastContact = "last_contact"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldMachineId holds the string denoting the machineid field in the database.
	FieldMachineId = "machine_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldClusterId holds the string denoting the clusterid field in the database.
	FieldClusterId = "cluster_id"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the agent in the database.
	Table = "agents"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "nodes"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "nodes"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "agent_node"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "agents"
	// OwnerInverseTable is the table name for the Cluster entity.
	// It exists in this package in order to avoid circular dependency with the "cluster" package.
	OwnerInverseTable = "clusters"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "cluster_agents"
)

// Columns holds all SQL columns for agent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOnline,
	FieldVersion,
	FieldIpv4,
	FieldIpv6,
	FieldPublicIpv4,
	FieldPublicIpv6,
	FieldLastContact,
	FieldDisabled,
	FieldUUID,
	FieldMachineId,
	FieldDescription,
	FieldClusterId,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "agents"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"cluster_agents",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() time.Time
	// UpdateDefaultDeletedAt holds the default value on update for the "deleted_at" field.
	UpdateDefaultDeletedAt func() time.Time
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// Ipv4Validator is a validator for the "ipv4" field. It is called by the builders before save.
	Ipv4Validator func(string) error
	// Ipv6Validator is a validator for the "ipv6" field. It is called by the builders before save.
	Ipv6Validator func(string) error
	// PublicIpv4Validator is a validator for the "public_ipv4" field. It is called by the builders before save.
	PublicIpv4Validator func(string) error
	// PublicIpv6Validator is a validator for the "public_ipv6" field. It is called by the builders before save.
	PublicIpv6Validator func(string) error
	// DefaultLastContact holds the default value on creation for the "last_contact" field.
	DefaultLastContact func() time.Time
	// UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	UUIDValidator func(string) error
	// MachineIdValidator is a validator for the "machineId" field. It is called by the builders before save.
	MachineIdValidator func(string) error
)
