// Code generated by entc, DO NOT EDIT.

package k8sconnector

import (
	"time"
)

const (
	// Label holds the string label denoting the k8sconnector type in the database.
	Label = "k8s_connector"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldInCluster holds the string denoting the incluster field in the database.
	FieldInCluster = "in_cluster"
	// FieldBearerToken holds the string denoting the bearertoken field in the database.
	FieldBearerToken = "bearer_token"
	// FieldKubeConfig holds the string denoting the kubeconfig field in the database.
	FieldKubeConfig = "kube_config"
	// Table holds the table name of the k8sconnector in the database.
	Table = "k8sConnectors"
)

// Columns holds all SQL columns for k8sconnector fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldStatus,
	FieldMethod,
	FieldInCluster,
	FieldBearerToken,
	FieldKubeConfig,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() time.Time
	// UpdateDefaultDeletedAt holds the default value on update for the "deleted_at" field.
	UpdateDefaultDeletedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
)
